@startuml

用户 -> 商户系统后台: 1、平台下单，发起支付()

商户系统后台 -> 商户系统后台: 2、生成平台订单()

商户系统后台 -> 微信支付系统: 3、请求下单接口、创建订单()

微信支付系统 -> 微信支付系统: 4、生成预付单

微信支付系统 -> 商户系统后台: 5、返回预付单标识()

商户系统后台 -> 商户系统后台: 6、生成带签名的支付信息()

用户 -> 商户系统后台: 7、发起支付()

用户 -> 微信客户端: 8、调起微信支付()

微信客户端 -> 微信支付系统: 9、发起支付请求()

微信支付系统 -> 微信支付系统: 10、验证支付授权权限()

微信支付系统 -> 微信客户端: 11、返回支付授权()

用户 -> 微信客户端: 12、确认支付，输入密码()

微信支付系统 -> 微信客户端: 13、提交授权()

微信支付系统 -> 微信支付系统: 14、验证授权()

微信支付系统 -> 商户系统后台: 15、异步通知平台支付结果()

商户系统后台 -> 商户系统后台: 16、保存支付通知()

商户系统后台 -> 微信支付系统: 17、返回告知成功接收处理()

微信支付系统 -> 微信客户端: 18、返回支付结果，并发微信消息提醒()

微信客户端 -> 商户系统后台: 19、支付状态查询()

商户系统后台 -> 微信支付系统: 20、调用查单接口，查询支付结果()

微信支付系统 -> 商户系统后台: 21、返回支付结果()

微信支付系统 -> 微信客户端: 22、展示支付消息()
@enduml